title: Machine Unlearning
description: Exploring techniques to make models forget information.
theme: jekyll-theme-tactile
plugins:
- jekyll-katex
#remote_theme: pages-themes/tactile@v0.2.0
#plugins:
#- jekyll-remote-theme 
